---
image: debian:latest

before_script:
  - apt-get update -yqq
  - apt-get install -yqq perl make binutils findutils gzip tar wget nsis zip mkdocs git

pages:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - mkdir -p public
    - $(wget --no-check-certificate ${CI_PAGES_URL}/download.tar.gz -O download.tar.gz || exit 0)
    - '[ -s download.tar.gz ] && ( cd public ; tar -xzf ../download.tar.gz )'
    - git checkout master
    - git fetch --all --tags
    - git pull
    - git tag
    - git tag | tail -1
    - git rev-list $(git tag | tail -1) --max-count=1
    - git rev-list $(git rev-list $(git tag | tail -1) --max-count=1)..HEAD --count
    - git rev-list HEAD --max-count=3
    - echo $((git rev-list $(git rev-list $(git tag | tail -1) --max-count=1)..HEAD --count; echo 0 ) | head -1)
    - git log $(git describe --tags --abbrev=0 --always)..HEAD --oneline | wc -l
    - git log $(git tag | tail -1)..HEAD --oneline --max-count=999 | wc -l
    - git log $(git tag | tail -1)..HEAD --oneline --no-merges
    - make pkg
    - mv SWMB-Setup-*.exe public/
    - make version > public/version.txt
    - (cd dists/ocs-inventory/; make)
    - mv dists/ocs-inventory/SWMB-OCS-*.zip public/
    - (cd dists/wapt/; make)
    - mv dists/wapt/SWMB-WAPT-*.zip public/
    - (cd dists/uninstall-kaspersky/; make zip)
    - mv dists/uninstall-kaspersky/Kasperky-Uninstall-*.zip public/
    - rm -f public/SWMB-*-Latest.*
    - (cd public/; ln -sf $(ls -1t SWMB-Setup-*.exe | head -1) SWMB-Setup-Latest.exe)
    - (cd public/; ln -sf $(ls -1t SWMB-OCS-*.zip   | head -1) SWMB-OCS-Latest.zip)
    - (cd public/; ln -sf $(ls -1t SWMB-WAPT-*.zip  | head -1) SWMB-WAPT-Latest.zip)
    - (cd public/; ln -sf $(ls -1t Kasperky-Uninstall-*.zip  | head -1) Kasperky-Uninstall-Latest.zip)
    - echo '<html><body><h1>SWMB Setup and OCS / WAPT (zip) Package (last update ' $(date '+%Y/%m/%d %H:%M') UTC')</h1><ul>' > public/index.html
    - (cd public; while read file; do printf '<li>%s %s / <a href="%s">%s</a></li>\n' $(stat -c %y $file | cut -f 1,2 -d ':') $file $file; done < <(ls -1t *.exe *.zip) >> index.html)
    - echo '</ul></body></html>' >> public/index.html
    - (cd public ; tar --exclude '*-Latest.*' -czf ../download.tar.gz SWMB-Setup-*.exe SWMB-OCS-*.zip SWMB-WAPT-*.zip Kasperky-Uninstall-*.zip)
    - mv download.tar.gz public/
    - mkdir -p public/docs
    - make doc
    - cp -r /tmp/swmb/site/* public/docs/
  artifacts:
    paths:
      - public
  only:
    - master
