---
image: debian:latest

before_script:
  - apt-get update -yqq
  - apt-get install -yqq perl make binutils findutils gzip tar wget nsis zip mkdocs git dos2unix

pages:
  stage: build
  variables:
    # https://docs.gitlab.com/ee/user/project/repository/monorepos/index.html
    GIT_STRATEGY: clone
    GIT_DEPTH: 200
    KEEP_PKG: 50
  script:
    - mkdir -p public
    - $(wget --no-check-certificate ${CI_PAGES_URL}/download.tar.gz -O download.tar.gz || exit 0)
    - '[ -s download.tar.gz ] && ( cd public ; tar -xzf ../download.tar.gz )'
    - ls -t public/Kasperky-Uninstall-*.zip 2> /dev/null | tail -n +$((${KEEP_PKG} + 1)) | xargs -r rm -f
    - ls -t public/SWMB-WAPT-*.zip          2> /dev/null | tail -n +$((${KEEP_PKG} + 1)) | xargs -r rm -f
    - ls -t public/SWMB-OCS-*.zip           2> /dev/null | tail -n +$((${KEEP_PKG} + 1)) | xargs -r rm -f
    - ls -t public/SWMB-Setup-*.exe         2> /dev/null | tail -n +$((${KEEP_PKG} + 1)) | xargs -r rm -f
    - git checkout master
    - git fetch --all --tags
    - git tag
    - git rev-list $(git rev-list $(git tag | tail -1) --max-count=1)..HEAD --count
    - git log $(git tag | tail -1)..HEAD --oneline | wc -l
    - '[ $(git log $(git tag | tail -1)..HEAD --oneline | wc -l) -ge "${GIT_DEPTH}" ] && ( echo "Error: bad local numbering, variable GIT_DEPTH too small!" ; exit 111 )'
    - make pkg
    - mv SWMB-Setup-*.exe public/
    - make version > public/version.txt
    - (cd dists/ocs-inventory/; make)
    - mv dists/ocs-inventory/SWMB-OCS-*.zip public/
    - (cd dists/wapt/; make)
    - mv dists/wapt/SWMB-WAPT-*.zip public/
    - (cd dists/uninstall-kaspersky/; make zip)
    - mv dists/uninstall-kaspersky/Kasperky-Uninstall-*.zip public/
    - rm -f public/SWMB-*-Latest.*
    - (cd public/; ln -sf $(ls -1t SWMB-Setup-*.exe | head -1) SWMB-Setup-Latest.exe)
    - (cd public/; ln -sf $(ls -1t SWMB-OCS-*.zip   | head -1) SWMB-OCS-Latest.zip)
    - (cd public/; ln -sf $(ls -1t SWMB-WAPT-*.zip  | head -1) SWMB-WAPT-Latest.zip)
    - (cd public/; ln -sf $(ls -1t Kasperky-Uninstall-*.zip  | head -1) Kasperky-Uninstall-Latest.zip)
    - echo '<html><body><h1>SWMB Setup and OCS / WAPT (zip) Package (last update ' $(date '+%Y/%m/%d %H:%M') UTC')</h1><ul>' > public/index.html
    - (cd public; while read file; do printf '<li>%s %s / <a href="%s" style="width:17em; display:inline-block;">%s</a> (SHA-1 %s)</li>\n' $(stat -c %y $file | cut -f 1,2 -d ':') $file $file $(shasum -a 1 $file | cut -f 1 -d ' '); done < <(ls -1t *.exe *.zip) >> index.html)
    - echo '</ul></body></html>' >> public/index.html
    - (cd public ; tar --exclude '*-Latest.*' -czf ../download.tar.gz SWMB-Setup-*.exe SWMB-OCS-*.zip SWMB-WAPT-*.zip Kasperky-Uninstall-*.zip)
    - mv download.tar.gz public/
    - mkdir -p public/docs
    - make doc
    - cp -r /tmp/swmb/site/* public/docs/
  artifacts:
    paths:
      - public
  only:
    - master
