site_name: SWMB - Secure Windows Mode Batch
site_url: https://resinfo-gt.pages.in2p3.fr/swmb/resinfo-swmb/docs
docs_dir: __HERE__
site_dir: /tmp/swmb/site
site_author: RESINFO GT SWMB
copyright: Copyright (C) 2020-2025, CNRS, France (document generated on __DATE__)

nav:
    - Home: README.md
    - Use case (distribution): dists/README.md
    - Contributing: CONTRIBUTING.md
    - Faq: FAQ.md
    - News: NEWS.md
    - Authors: AUTHORS.md
    - License: LICENSE.md
    - References: REFERENCES.md

theme:
  name: material
  locale: fr
  features:
    - content.code.copy
    - search.highlight
    - search.suggest
  palette:
    primary: pink
    accent: red

plugins:
  - macros
  - search

markdown_extensions:
  - admonition:
  - pymdownx.emoji:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list:
