#!/bin/bash
#
# make-swce
#
# 2026/02/10 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>

cat <<END
END

for func in SWMB_LoadIniFile \
  SWMB_GetRegistrySettings \
  SWMB_GetIniSettings \
  SWMB_WriteSettings
do
  echo ''
  echo '################################################################'
  echo ''
  ./extract-swce "${func}" ../../Modules/SWMB.psm1
done

for tweak in $(cat LocalMachine-SWCE.preset)
do
  echo ''
  echo '################################################################'
  echo ''
  ./extract-swce "Tweak${tweak}" ../../Modules/SWMB/*.psm1
done

cat <<END

################################################################
################################################################

# RUN

END

for tweak in $(cat LocalMachine-SWCE.preset)
do
  echo "Tweak${tweak}"
done
echo ''
