#!/bin/bash
#
# make-swce
#
# 2026/02/10 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>


# BOM UTF-8
echo -e '\xEF\xBB\xBF'

cat <<'END'
################################################################
END

for func in SWMB_LoadIniFile \
  SWMB_GetRegistrySettings \
  SWMB_GetHashSettings \
  SWMB_GetIniSettings \
  SWMB_WriteSettings
  TweakSysRequireAdmin
do
  echo '################################################################'
  echo ''
  ./extract-swce "${func}" ../../Modules/SWMB.psm1
  echo ''
done

cat <<'END'
################################################################
END

for tweak in $(cat LocalMachine-SWCE.preset | sed -e 's/#.*//; s/[[:space:]]$//;' | awk '{print $1}' | grep .)
do
  echo '################################################################'
  echo ''
  ./extract-swce "Tweak${tweak}" ../../Modules/SWMB/*.psm1
  echo ''
done

cat <<END
################################################################
################################################################

# RUN

TweakSysRequireAdmin

END

urlref='https://system32.eventsentry.com/stig/viewer'
cat <<'END' 1>&2
| Rule Name       | Description |
|-----------------|-------------|
END

for tweak in $(cat LocalMachine-SWCE.preset | sed -e 's/#.*//; s/[[:space:]]$//;' | awk '{print $1}' | grep .)
do
  comment=$(grep "\b${tweak}\b" ../../Presets/LocalMachine-All.preset | awk -F '##' '{print $2}' | sed -e 's/^[[:space:]]//;' | head -1)
  doc=$(echo "${comment}" | sed -e "s#\(W[[:digit:]][[:digit:]][[:space:]]STIG V-[[:digit:]][[:digit:]]*\)[[:space:]]\(https\?://[^[:space:]]\+\)#[\1](\2)#g; s/[[:space:]]\+$//;")
  printf "| %-32s | %s |\n" "\`${tweak}\`" "${doc}" 1>&2
  printf "Tweak%-32s ## %s\n" "${tweak}" "${comment}"
  echo 'Write-Output ""'
done
echo ''
