#!/bin/bash
#
# make-swce
#
# 2026/02/10 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>

cat <<END
END

for func in SWMB_LoadIniFile \
  SWMB_GetRegistrySettings \
  SWMB_GetIniSettings \
  SWMB_WriteSettings
do
  echo ''
  echo '################################################################'
  echo ''
  ./extract-swce "${func}" ../../Modules/SWMB.psm1
done

for tweak in $(cat LocalMachine-SWCE.preset)
do
  echo ''
  echo '################################################################'
  echo ''
  ./extract-swce "Tweak${tweak}" ../../Modules/SWMB/*.psm1
done

cat <<END

################################################################
################################################################

# RUN

END

urlref='https://system32.eventsentry.com/stig/viewer'

for tweak in $(cat LocalMachine-SWCE.preset | sed -e 's/#.*//; s/[[:space:]]$//;' | awk '{print $1}' | grep .)
do
  comment=$(grep "\b${tweak}\b" ../../Presets/LocalMachine-All.preset | awk -F '##' '{print $2}' | sed -e 's/^[[:space:]]//;' | head -1)
  doc=$(echo "${comment}" | sed -e "s#https\?://[^[:space:]]\+##g; s#\(STIG \(V-[[:digit:]][[:digit:]]*\)\)#[\1](${urlref}/\2)#g; s/[[:space:]]\+$//;")
  printf "| %-32s | %s |\n" "${tweak}" "${doc}" 1>&2
  printf "Tweak%-32s ## %s\n" "${tweak}" "${comment}"
done
echo ''
